spring.application.name=backend
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.flyway.locations=classpath:migrations
allowed.origins=http://localhost:5173,https://ukaytwo-web-frontend.onrender.com
jwt.secret=${JWT_SECRET}
